FROM tensorflow/tensorflow:2.4.1-gpu

RUN rm /etc/apt/sources.list.d/cuda.list
RUN rm /etc/apt/sources.list.d/nvidia-ml.list
RUN apt-key del 7fa2af80
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub

RUN apt-get update && apt-get install -y tmux ffmpeg libsm6 libxext6 libxrender-dev wget unrar unzip

# Install Atari environment seedrl style
RUN pip3 install gym[atari]==0.18.3
RUN pip3 install atari-py
RUN wget https://github.com/Kitware/CMake/releases/download/v3.27.7/cmake-3.27.7-linux-x86_64.tar.gz
RUN mkdir /workspace
RUN mkdir /workspace/cmake
RUN tar -xvzf cmake-3.27.7-linux-x86_64.tar.gz -C /workspace/cmake
ENV PATH="${PATH}:/workspace/cmake/cmake-3.27.7-linux-x86_64/bin"
RUN apt-get install -y git
RUN pip3 install tensorflow_probability==0.11.0

# Install standalone ALE (without gym)
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y git-all \
    build-essential \
    cmake

RUN git clone --depth 1 --branch v0.6.1 https://github.com/mgbellemare/Arcade-Learning-Environment.git /workspace/Arcade-Learning-Environment

RUN cd /workspace/Arcade-Learning-Environment && mkdir build
RUN cd /workspace/Arcade-Learning-Environment/build && cmake -DUSE_SDL=OFF -DUSE_RLGLUE=OFF -DBUILD_EXAMPLES=ON ..
RUN cd /workspace/Arcade-Learning-Environment/build && make -j 4

RUN cd /workspace/Arcade-Learning-Environment && pip3 install .

RUN pip3 install numpy
RUN pip3 install pygame

# add opengl support to container, see also
# https://medium.com/@benjamin.botto/opengl-and-cuda-applications-in-docker-af0eece000f1
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-opengl \
    mesa-utils \
    libglvnd0 \
    libgl1 \
    libglx0 \
    libegl1 \
    libxext6 \
    libx11-6 \
    freeglut3-dev

# add nvidia display to container, see also URL above
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
